### ISSUE TITLE
Vefa lookup return "Invalid response from SMP." for partcipiant : "0037:000000000" in TEST : https://test-vefa.difi.no/smp/0037/000000000

### ISSUE THREAD

**Issue by aaron-kumar** [difi/vefa-smp-lookup#1]
Vefa lookup return "Invalid response from SMP." for participant : "0037:000000000" in TEST : https://test-vefa.difi.no/smp/0037/000000000

Though, I can lookup up same participiant via PEPPOL Practical:
https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=0037%3A000000000&sml=digittest&action=perform

**Comment by klakegg** [comment]
Not reproducible.
